# Copyright (c) 2021 Mike "KemoNine" Crosson
# SPDX-License-Identifier: MIT

# Tune combos for ARDUX
CONFIG_ZMK_COMBO_MAX_COMBOS_PER_KEY=24
CONFIG_ZMK_COMBO_MAX_KEYS_PER_COMBO=8
CONFIG_ZMK_COMBO_MAX_PRESSED_COMBOS=8

# Bluetooth
CONFIG_BT_MAX_CONN=6
CONFIG_BT_MAX_PAIRED=6

# Bluetooth device name
CONFIG_ZMK_KEYBOARD_NAME="PJs Keyboard"
CONFIG_BT_DEVICE_NAME_MAX=32

# OLED display
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_WORK_QUEUE_DEDICATED=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILTIN=y
CONFIG_ZMK_WPM=y

# External power — forces VCC rail ON for OLED
# The nice!nano v2 gates VCC via GPIO P0.13
# Without this the OLED gets no power
CONFIG_ZMK_EXT_POWER=y

# Mouse support
CONFIG_ZMK_POINTING=y

# Sleep off while learning the board
CONFIG_ZMK_SLEEP=n
